version: "3"
services:
  nodeserver:
    build:
      context: ./
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
  nginx:
    restart: always
    build:
      context: ../nginx
    ports:
      - "80:80"