version: "3"
services:
  task:
    build:
      context: ../epg-now-task_manager
  nodeserver:
    build:
      context: ./
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
  nginx:
    restart: always
    build:
      context: ../nginx
    ports:
      - "80:80"
